
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_demo'
version: '1.0.0'

# This setting configures which "profile" (within profiles.yml) dbt uses for this project.
profile: 'dbt_demo'

vars:
  surrogate_key_treat_nulls_as_empty_strings: True

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["src/models"]  # list of folder that contain models
analysis-paths: ["src/analyses"]
test-paths: ["tests"]
seed-paths: ["src/seeds"]
macro-paths: ["src/macros"]
snapshot-paths: ["src/snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models: https://docs.getdbt.com/docs/configuring-models
models:
  dbt_demo:
    # Config indicated by + and applies to all files under models/use_case_3/
    use_case_3:
      +materialized: view