dbt_demo:
  outputs:
    dev:
      catalog: marcin_demo
      schema: dbt
      threads: 1
      type: databricks
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "/sql/1.0/warehouses/{{ env_var('DBT_CLUSTER_ID') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
  target: dev