version: 2

models:
  - name: my_python_model

    # Document within the same codebase
    description: My transformation written in Python

    # Configure in ways that feel intuitive and familiar
    config:
      materialized: table
      # defined in dbt_project.yml
      #tags: ['python']
      #submission_method: all_purpose_cluster
      #create_notebook: False
      #cluster_id: 0709-132523-cnhxf2p6

    # Test the results of my Python transformation
    columns:
      - name: carat
        # Standard validation for 'grain' of Python results
        data_tests:
          - not_null
    data_tests:
      # Write your own validation logic (in SQL) for Python results
      - diamonds_check