version: 2

sources:
  - name: raw # name is used for selecting the specific source
    database: hive_metastore
    schema: default
    tables:
      - name: diamonds  # specifies hive_metastore.default.diamonds table
